"""Paths and I/O shared by the paper figure/table builders (no ibUMAP import needed).

Every builder reads frozen result summaries from ``paper/data/`` (or another
directory with the same layout, via ``--data-dir``) and writes to
``paper/build/`` (``--build-dir``):

    paper/build/figures/   PDF figures, named as in the manuscript
    paper/build/tables/    LaTeX table rows (``\\input`` by the manuscript), plot-data CSVs, evidence JSON
"""
from __future__ import annotations

import argparse
import csv
import gzip
import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_DATA = REPO / "paper" / "data"
DEFAULT_BUILD = REPO / "paper" / "build"


class Paths:
    def __init__(self, data: Path, build: Path) -> None:
        self.data = Path(data).resolve()
        self.build = Path(build).resolve()
        self.figures = self.build / "figures"
        self.tables = self.build / "tables"
        for directory in (self.figures, self.tables):
            directory.mkdir(parents=True, exist_ok=True)


def parse_args(description: str, extra=None) -> tuple[argparse.Namespace, Paths]:
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA,
                        help="frozen result summaries (default: paper/data)")
    parser.add_argument("--build-dir", type=Path, default=DEFAULT_BUILD,
                        help="output directory (default: paper/build)")
    if extra is not None:
        extra(parser)
    args = parser.parse_args()
    return args, Paths(args.data_dir, args.build_dir)


def sha256(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def read_csv(path: Path) -> list[dict[str, str]]:
    path = Path(path)
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def read_json(path: Path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def check_group(paths: Paths, group: str) -> dict[str, str]:
    """Verify the files of one data group against paper/data/MANIFEST.json, if present.

    A directory produced by a fresh (L2) run may omit the manifest; then the
    hashes are only reported.
    """
    manifest_path = paths.data / "MANIFEST.json"
    if not manifest_path.exists():
        return {}
    files = read_json(manifest_path)["groups"][group]["files"]
    for name, expected in files.items():
        actual = sha256(paths.data / name)
        if actual != expected:
            sys.exit(f"{name}: SHA-256 {actual} does not match MANIFEST.json ({expected})")
    return files


def write_rows(paths: Paths, name: str, rows: list[str], builder: str) -> Path:
    """Write LaTeX table rows with a one-line provenance banner."""
    path = paths.tables / name
    path.write_text(f"% Generated by scripts/paper/{builder} from paper/data.\n" + "\n".join(rows) + "\n")
    return path


def write_csv(path: Path, rows: list[dict]) -> None:
    with Path(path).open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, obj) -> None:
    Path(path).write_text(json.dumps(obj, indent=2) + "\n")


def configure_matplotlib_environment() -> None:
    # Keep font/cache writes out of the repository.
    os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "ibumap-paper-mpl"))
    os.environ.setdefault("XDG_CACHE_HOME", str(Path(tempfile.gettempdir()) / "ibumap-paper-cache"))
