#!/usr/bin/env python3
"""Section 4 appendix tables from the frozen mechanism experiment (59 datasets).

Writes to paper/build/tables/:
  ch4_quality_rows.tex   tab:mechanism-quality  (variant means, datasets weighted equally)
  ch4_effect_rows.tex    tab:mechanism-effects  (median paired change and number of improving datasets)
  ch4_family_rows.tex    tab:mechanism-family   (families weighted equally)
  ch4_dataset_means.csv, ch4_quality_means.csv, ch4_family_means.csv, ch4_family_equal_means.csv,
  ch4_effect_statistics.csv, ch4_workloads.csv, ch4_evidence.json
"""
from __future__ import annotations

import pandas as pd

import _mechanism as mech
from _common import parse_args, write_json

BUILDER = "ch4_tables.py"
CONTRASTS = [("B--A", "synchrony", "umap_learn", "sync_sampled"),
             ("C--B", "sampling_to_event_expectation", "sync_sampled", "sync_expected"),
             ("D--C", "event_to_degree_raw_formulation", "sync_expected", "sync_direct"),
             ("E--D", "scalar_kernel_cap", "sync_direct", "sync_direct_capped"),
             ("F--E", "fft_approximation", "sync_direct_capped", "sync_fft"),
             ("G--F", "safeguard_bundle", "sync_fft", "sync_fft_guarded"),
             ("H--G", "production_residual", "sync_fft_guarded", "ibumap_production"),
             ("H--A", "production_vs_umap", "umap_learn", "ibumap_production"),
             ("B + norm clip -- B", "sampled_norm_clip", "sync_sampled", "sync_sampled_clip")]


def variant_rows(data, names=True, metrics=mech.ALL_METRICS):
    lines = [f"% Generated by scripts/paper/{BUILDER} from paper/data."]
    for ident, algo, label in mech.VARIANTS:
        if ident == "H":
            lines.append(r"\midrule")
        numbers = " & ".join(f"{data.loc[algo, m]:.4f}" for m in metrics)
        lines.append((f"{ident}. {label}" if names else ident) + " & " + numbers + r" \\")
    return "\n".join(lines) + "\n"


def main() -> None:
    _, paths = parse_args(__doc__.splitlines()[0])
    raw, workloads, hashes = mech.load_scores(paths)
    per = mech.per_dataset_means(raw)
    means = per.groupby("algorithm").mean()
    family = per.groupby(["family", "algorithm"]).mean()
    balanced = family.groupby("algorithm").mean()

    effects = []
    effect_lines = [f"% Generated by scripts/paper/{BUILDER} from paper/data.",
                    "% Median signed improvement (number improving); all metrics higher-is-better."]
    for label, _contrast, a, b in CONTRASTS:
        if label in ["H--A", "B + norm clip -- B"]:
            effect_lines.append(r"\midrule")
        diff = per.xs(b, level="algorithm") - per.xs(a, level="algorithm")
        cells = []
        for metric in mech.ALL_METRICS:
            x = diff[metric]
            improved, worse = int((x > mech.TIE).sum()), int((x < -mech.TIE).sum())
            cells.append(f"${x.median():+.4f}$ ({improved})")
            effects.append(dict(contrast=label, metric=metric, mean=x.mean(), median=x.median(),
                                median_absolute=x.abs().median(), improved=improved, worse=worse, n=len(x)))
        effect_lines.append(label + " & " + " & ".join(cells) + r" \\")

    out = paths.tables
    (out / "ch4_quality_rows.tex").write_text(variant_rows(means))
    (out / "ch4_family_rows.tex").write_text(variant_rows(balanced, False))
    (out / "ch4_effect_rows.tex").write_text("\n".join(effect_lines) + "\n")
    order = [a for _, a, _ in mech.VARIANTS]
    per.to_csv(out / "ch4_dataset_means.csv")
    means.loc[order].to_csv(out / "ch4_quality_means.csv")
    family.to_csv(out / "ch4_family_means.csv")
    balanced.loc[order].to_csv(out / "ch4_family_equal_means.csv")
    pd.DataFrame(effects).to_csv(out / "ch4_effect_statistics.csv", index=False)
    datasets = [{k: d[k] for k in ("name", "n", "family")} for d in workloads["datasets"]]
    pd.DataFrame(datasets).sort_values(["n", "name"]).to_csv(out / "ch4_workloads.csv", index=False)
    write_json(out / "ch4_evidence.json", dict(
        data="paper/data/mechanism", source_sha256=hashes,
        aggregation="Average optimizer seeds within each workload, then average the 59 retained workloads "
                    "equally; deterministic aliases are not independent repeats.",
        family_sensitivity="Average workloads within each of five families, then average families equally.",
        selection=workloads["selection"], variants=mech.VARIANTS, metrics=mech.ALL_METRICS,
        global_configuration=workloads["global_configuration"], datasets=datasets))
    print(f"{BUILDER}: wrote 3 tables and 7 data files to {out}")


if __name__ == "__main__":
    main()
